### PR TITLE
fix: Padding for 'How it works' fixes

### LINKED ISSUE #210: Style: Padding of 'How it work' section for RWD
### Description

I noticed that the padding of the 'How it works' section creates a lot of whitespace.

I would like to work on the responsiveness on this section so that the site displays well on smaller screens.

### Screenshots

how-it-works-section

### PR DESCRIPTION
**Pull request by TreciaKS**
### 🛠️ Fixes Issue
Closes #210 

### ➕ Changes Introduced
Padding and margin fix on the "How it works" section (Features.tsx file). 

### 📷 Screenshots
Before (pb-14)
Screenshot 2022-10-29 at 11 23 38

After (pb-4)
Screenshot 2022-10-29 at 11 23 10

features tsx

Heading
Before (pt-20, mt-20)
Screenshot 2022-10-29 at 11 33 33

After  (pt-10, mt-10)
Screenshot 2022-10-29 at 11 33 14

paddingTitle

### CODE REVIEW

**Review by adilwahla — COMMENTED** [review]
you should improve your title follow title guide line

**Comment by TreciaKS** [comment]
I did precisely so. I passed all 4 checks and had already provided screenshot to the changes I've made. :)

File: src/components/Features.tsx [hunk 1]
```diff
@@ -145,7 +145,7 @@ export function Features() {
     <section
       id='how-it-works'
       aria-label='Features for simplifying everyday business tasks'
-      className='bg-white pt-20 pb-14 sm:pb-20 sm:pt-32 lg:pb-32'
```
Comment (subhoghoshX) [inline src/components/Features.tsx:148]: Removing `pb-14` makes sense, but why add `pb-4`?

Comment (TreciaKS) [reply src/components/Features.tsx:148]: It creates an equal distance in the title or heading, below and above. One finger apart, equally

Comment (TreciaKS) [reply src/components/Features.tsx:148]: Screenshot 2022-10-30 174331
It removes the extra padding after the `<hr>` tag or line divider, makes it much neater to something like this:

Screenshot 2022-10-30 174534

As I've mentioned before, the screenshots of the site and the code itself are provided for you to see the changes in correlation to why/ and where the changes have been made :)

Comment (subhoghoshX) [reply src/components/Features.tsx:148]: Sorry, the preview of this project is not quite working at the moment, that's why I can't see the deployed version.

> It removes the extra padding after the `<hr>` tag or line divider, makes it much neater to something like this:

Yeah, I got that part. My question was why add `pb-4`, wouldn't it add some extra padding again?

Comment (TreciaKS) [reply src/components/Features.tsx:148]: No, no extra padding at all.  Why? I reduced the padding from `pb-14` to `pb-4` for the reason you've quoted from me :)

Comment (subhoghoshX) [reply src/components/Features.tsx:148]: Ended up cloning your repo. It shows this padding that I was referring to :point_down:

screenshot-showing-extra-space

Comment (TreciaKS) [reply src/components/Features.tsx:148]: Hello there, forgive my late response. I guess i will revert the changes then and leave that bottom as is.

Comment (subhoghoshX) [reply src/components/Features.tsx:148]: We're all working on it in our spare time, so don't worry. I appreciate whatever contribution you make.

Going back to the padding issue. My point was, you should probably remove the padding completely instead of just reducing it. I think that's what you intended to do in the first place.

Comment (TreciaKS) [reply src/components/Features.tsx:148]: Thank you very much

Okay, to remove the padding completely, got it! Tbh, I'm not sure what I intended to do 😂

Comment (subhoghoshX) [reply src/components/Features.tsx:148]: Haha no worries. Thanks for working on it.

**Review by subhoghoshX — APPROVED** [review]
